name: taobaokeapi
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://taobaokeapi.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  dio: ^3.0.10

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
